"""add phone_key and whatsapp_key to listing

Revision ID: 3c18406ca0f4
Revises: 8829860d4a26
Create Date: 2026-02-02 18:55:31.483189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c18406ca0f4'
down_revision = '8829860d4a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_key', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_key', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_listing_phone_key'), ['phone_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_listing_whatsapp_key'), ['whatsapp_key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_whatsapp_key'))
        batch_op.drop_index(batch_op.f('ix_listing_phone_key'))
        batch_op.drop_column('whatsapp_key')
        batch_op.drop_column('phone_key')

    # ### end Alembic commands ###
